version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: apt update && apt-get -y install build-essential git sudo wget cmake libssl-dev libgmp-dev autoconf libtool
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake . && make
      - run: export GTEST_COLOR=1 && ctest -VV

workflows:
  version: 2
  build_all:
    jobs:
      - build
