name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install deps
        run: |
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
          make deps
          brew install conan
      - run: cmake -DCMAKE_BUILD_TYPE=Debug . && make
      - run: GTEST_COLOR=1 ASAN_OPTIONS=detect_leaks=0 ctest -VV