name: Build
on: [push]

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install deps
        run: |
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
          make deps
          brew install conan
      - run: cmake -DCMAKE_BUILD_TYPE=Debug . && make
      - run: GTEST_COLOR=1 ASAN_OPTIONS=detect_leaks=0 ctest -VV

  build_only_rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install deps
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      - name: rustfmt
        run: |
          cd ./app/rust
          cargo fmt --version
          cargo fmt -- --check
      - name: clippy
        run: |
          cd ./app/rust
          cargo clippy --version
          cargo clippy --all-features --all-targets || true
      - name: audit
        run: |
          cd ./app/rust
          cargo audit --version
          cargo audit
      - name: run tests
        run: |
          cd ~/project/app/rust
          cargo test

  build_ledger:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: zondax/builder-bolos:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
    env:
      BOLOS_SDK: /home/zondax/project/deps/nanos-secure-sdk
      BOLOS_ENV: /opt/bolos
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Standard app
        run: |
          source /home/zondax/.cargo/env
          make
      - name: Build SR25519 app
        run: |
          source /home/zondax/.cargo/env
          SUPPORT_SR25519=1 make
      - name: Build Ledgeracio
        run: |
          source /home/zondax/.cargo/env
          COIN=Ledgeracio make